blank_issues_enabled: false
contact_links:
  - name: Start a Discussion
    about: "Start a discussion to share your experience with creedengo-infra"
    url: https://github.com/green-code-initiative/creedengo-infra/discussions/new/choose
