name: Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  packages: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout tag "${{ github.ref_name }}"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

  publish-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag "${{ github.ref_name }}"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Publish package on GitHub Packages
        run: npm publish
        working-directory: eslint-plugin
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
